name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  site:
    name: 'Build website and demonstrator'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Build site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./website
        run: |
          npm install
          npm run build
      - uses: docker://pandoc/latex:2.9
        with:
          args: "-s ./paper/src/main.tex -o ./paper/output/paper.html --number-sections --template ./paper/template/template.html--cite"
      - name: Copy paper to website
        working-directory: ./
        run: |
          cp -r ./paper/output/paper.html ./website/_site/paper.html
          cp -r ./paper/src/images ./website/_site/images
      # - name: Build example application
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   working-directory: ./demonstrator
      #   run: |
      #     npm install
      #     npm run build
      #     cp -r ./dist ../../website/_site/demonstrator
      - name: Deploy site to GitHub
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/_site